# actor name
ACTOR_NAME={{actor_description.actor_name}}

FC={{ code_description.settings.compiler_cmd }}

MPIFC={{ code_description.settings.mpi_compiler_cmd or ''}}

WRAPPER_DIR=$(dir $(realpath $(firstword $(MAKEFILE_LIST))))

OPENMPFLAG={{ code_description.settings.open_mp_switch or '' }}

MOD_DIR=./build/

#TO DO - any clever way to do this?
ifeq ($(FC), ifort)
# INTEL
  FLAGS=-g -fPIC -module $(MOD_DIR)
else
# GFORTRAN
 FLAGS=-g -fPIC -J$(MOD_DIR)
endif

FCLAGS=$(FLAGS) $(OPENMPFLAG)
CODE_LIB_FILE=$(notdir {{code_description.implementation.code_path}})
CODE_LIB_DEF=./lib/$(CODE_LIB_FILE)

# main IMAS libs to be used
CORE_LIBS_FLAGS:= $(shell pkg-config --cflags "imas-$(FC)")
CORE_LIBS:=$(shell pkg-config --libs "imas-$(FC)")

# required libs published using pkg-config mechanism
{% if code_description.settings.extra_libraries.pkg_config_defined %}
LIBS_PKGCONFIG_DEFINED_NAMES={{ (code_description.settings.extra_libraries.pkg_config_defined or []) | join(' ')}}
LIBS_PKGCONFIG_DEFINED_FLAGS=$(shell pkg-config --cflags $(LIBS_PKGCONFIG_DEFINED_NAMES))
LIBS_PKGCONFIG_DEFINED=$(shell pkg-config --libs $(LIBS_PKGCONFIG_DEFINED_NAMES))
{% else %}
LIBS_PKGCONFIG_DEFINED_NAMES=
LIBS_PKGCONFIG_DEFINED_FLAGS=
LIBS_PKGCONFIG_DEFINED=
{% endif %}

# required libs provided by user as a path
LIBS_PATH_DEFINED=
{%- for lib_path in code_description.settings.extra_libraries.path_defined or [] %}
 ./extra-libs/{{ lib_path | basename }}
{%- endfor %}

INCLUDES=-I./include $(CORE_LIBS_FLAGS) $(LIBS_PKGCONFIG_DEFINED_FLAGS)
LIBS=$(CORE_LIBS) $(LIBS_PKGCONFIG_DEFINED) $(LIBS_PATH_DEFINED) $(CODE_LIB_DEF)

{% if code_description.settings.mpi_compiler_cmd   %}

# MPI compilation wrapper will be used
FC=$(MPIFC)
{% endif %}


all: ../bin/$(ACTOR_NAME).exe   ../lib/lib$(ACTOR_NAME).so

../bin/$(ACTOR_NAME).exe: src/standalone.f90 build/defs.o build/RWTools.o build/fortrantools.o build/fortran_wrapper.o
	@echo "   * $^ -> $@"
	@mkdir -p ../bin
	$(FC) $(FCLAGS) -o $@ -Wl,--start-group $^ $(INCLUDES) -I$(MOD_DIR) $(LIBS) -Wl,--end-group -Wl,-rpath,$(WRAPPER_DIR)/extra-libs/

build/%.o: src/%.f90
	@echo "  * $< -> $@"
	@mkdir -p ./build
	$(FC) $(FCLAGS) -c -w $^ -o $@  $(INCLUDES)

../lib/lib$(ACTOR_NAME).so: build/defs.o build/fortran_wrapper.o  build/RWTools.o build/fortrantools.o
	@echo "   * $^ -> $@"
	@mkdir -p ../lib
	$(FC) $(FCLAGS) -shared -o $@ -Wl,--start-group $^ $(LIBS) -Wl,--end-group -Wl,-rpath,$(WRAPPER_DIR)/lib_ext/def/



clean:
	-rm -f *.o build/* ../lib/*.so ../bin/*
