export # export all variables to 'sub-Makefiles'

ACTOR_NAME=code_lifecycle
ACTOR_TYPE=muscle3-fortran
CODE_LANGUAGE=fortran
WRAPPED_CODE_NAME=basic

clean wrapped actor actor-gui wf-run check-output test:
	$(MAKE) -f $(TESTS_DIR)/Makefile $@