export # export all variables to 'sub-Makefiles'

ACTOR_NAME=basic_python
ACTOR_TYPE=muscle3-python
CODE_LANGUAGE=python
WRAPPED_CODE_NAME=basic

clean wrapped actor actor-gui wf-run check-output test:
	$(MAKE) -f $(TESTS_DIR)/Makefile $@
