export # export all variables to 'sub-Makefiles'

ACTOR_NAME=basic_cpp
ACTOR_TYPE=muscle3-cpp
CODE_LANGUAGE=cpp
WRAPPED_CODE_NAME=basic

clean wrapped actor actor-gui wf-run check-output test:
	$(MAKE) -f $(TESTS_DIR)/Makefile $@

