# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: iWrap Tutorial
author: Agata Filipczak, Aleksander Wisznowski, Michał Owsiak, Bartek Palak

# theme:
#   name: jupyter-book

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 540
  kernel_name: bash




# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# launch_buttons:
#   thebe : true  

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
  #  nb_merge_streams: true
  #   html_theme: 'sphinx_rtd_theme'
  extra_extensions:
  - sphinx_inline_tabs

