# _config.yml
title: iWrap Documentation
author: PSNC Poznan team - Bartek Palak, Jędrzej Wasik, Agata Filipczak, Aleksander Wisznowski, Bartłomiej Pogodziński
logo: images/imas.png

execute:
  execute_notebooks: cache
  timeout: 540

exclude_patterns:
  - "tutorial_venv/*"
  - "README.md"
  - "documentation/template.rst"

#
sphinx:
  recursive_update: true
  config:
    html_theme_options:
      show_navbar_depth: 3      #left sidebar
      show_toc_level: 3         #rigth sidebar
