# _config.yml
title: iWrap Documentation
author: PSNC Poznan team - Bartek Palak, Jędrzej Wasik, Agata Filipczak, Aleksander Wisznowski, Bartłomiej Pogodziński
logo: images/imas.png

execute:
  execute_notebooks: cache
  timeout: 540

exclude_patterns:
  - "tutorial_venv/*"
  - "README.md"

#
sphinx:
  recursive_update: true

  extra_extensions:
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.autosummary'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.viewcode'
    - 'sphinx.ext.extlinks'
    - 'sphinx.ext.intersphinx'
#  'immaterial' theme cannot be used due to incompatibilities between sphinx-8.0.2 vs sphinx_immaterial-0.12.2
#    - "sphinx_immaterial"
#    - "sphinx_immaterial.apidoc.python.apigen"
  config:
#    html_theme: "sphinx_immaterial"
    autosummary_generate: True
    autoclass_content: "both"
    add_module_names: False
    html_theme_options:
      show_navbar_depth: 3      #left sidebar
      show_toc_level: 3         #rigth sidebar
      repo_url: "https://git.iter.org/projects/IMEX/repos/iwrap"
      repo_name: "iWrap"
    suppress_warnings:
      - "etoc.toctree"

    autodoc_default_options:
      member-order: 'bysource'
      exclude-members': '__weakref__'
      members: True
      undoc-members: True
      show-inheritance: True
